### PR TITLE
Renamed honeybadger-ruby to neeto-bugtrap-ruby

### LINKED ISSUE #2: Rename honeybadger-ruby to neeto-bugtrap-ruby
@sruthy-j-mallya _a

### PR DESCRIPTION
**Pull request by sruthy-j-mallya**
Fixes #2 

@sandip-mane _a

I have renamed everything in honeybadger gem in the following way:
Honeybadger module -> NeetoBugtrapRuby
honeybadger folders-> neeto-bugtrap-ruby
honeybadger executable file -> neetobugtrap
honeybadger namespace -> neetobugtrap
method names having suffix honeybadger -> neetobugtrap
private instance variables having prefix hb -> nb.
Even though all the tests are successful, running the bundle exec neetobugtrap install API_KEY  command fails. When I debugged the issue, I found out that the instance variable callings is having []  and the notify method is also not called in test.rb file. Most probably it will be due to any mistakes while renaming. So I have verified it again to see if I renamed everything correctly. I couldn't find an issue in renaming. Could you please look into it?

Screenshot 2023-01-23 at 9 17 40 AM

### CODE REVIEW

**Comment by sandip-mane** [comment]
@sruthy-j-mallya _a there are still many `honeybadger` matches in the repo.
Please change it to neeto-bugtrap accordingly.

Here are the major changes that we want:
1. Remove `CHANGELOG.md`
2. Remove `TROUBLESHOOTING.md`
3. Remove `LICENSE`
4. Empty `README.md`
5. Update `.gemspec`
6. Rename the module to `NeetoBugtrap` (i.e. we should not use `NeetoBugtrapRuby` as the module name)
7. Update all ENV variable names too

Please assign it to me once done, I will check the issue with the commands.

**Comment by sruthy-j-mallya** [comment]
@sandip-mane 

Updated the changes mentioned.

Please review.

**Comment by sandip-mane** [comment]
@sandip-mane _a check the failure with the commands

**Review by sandip-mane — APPROVED** [review]

**Comment by sandip-mane** [comment]
@sruthy-j-mallya I've made some changes, the gem now calls the APIs when notices are triggered.
However, the install and test commands are still erroring out, I will create separate issues for you to take a look into it. I will be creating some issues for next course of actions.

The following config works in development:
```yaml
---
api_key: 'abcd'
connection:
  secure: false
  host: "api.lvh.me"
  port: 9033
report_data: true
```

**Pull request merged**
