### PR TITLE
Created the Semaphore config and added a Rubocop block

### PR DESCRIPTION
**Pull request by vivek-viswam-rv**
Part of: https://github.com/bigbinary/neeto-engineering-web/issues/277

@navaneethsdk _a Please add the `.rubocop.yml` file.

cc: @yedhink

### CODE REVIEW

**Comment by navaneethsdk** [comment]
@yedhink Should we add rubocop to this repo? Upon adding `.rubocop.yml` and running `bundle exec rubocop -A` the COP made about 4500 fixes across 169 files! And there are about 50 manual fixes to be applied. The number of manual fixes is not a problem but some of them involve complex class structure ordering which makes me skeptical about applying them. Later I found this was forked from `https://github.com/honeybadger-io/honeybadger-ruby`, hence the large difference in the standards.

**Comment by yedhink** [comment]
@sandip-mane Can you please comment on this? Questions:
- Why's this repo still maintained as a fork and not an independent BigBinary repo? Are we pulling changes from the parent?
- Can we apply the Rubocop config on all files and make necessary changes even if it's like 4500fixes across 169 files?

**Comment by sandip-mane** [comment]
> Why's this repo still maintained as a fork and not an independent BigBinary repo? Are we pulling changes from the parent?

We have forked it because we want to get the updates in the future from upstream.

> Can we apply the Rubocop config on all files and make necessary changes even if it's like 4500fixes across 169 files?

If we do so, we will not be able to update the repo with the latest changes from the upstream. Ref: https://github.com/bigbinary/neeto-bugtrap-ruby/pull/9#issuecomment-1429890419

@yedhink I think this repo can be kept as an exception from adding Rubocop changes. This is anyway a public-facing gem(not internal to neeto)

**Comment by yedhink** [comment]
>I think this repo can be kept as an exception from adding Rubocop changes.

Got it. @udai1931 Can you work with @sumanranjanpanda and add a flag in our list of products denoting that it's a public facing repo? This will help us in making a judgement on whether to add standardization changes to these repos or not.

Closing this issue.

**Pull request closed without merging**
