### PR TITLE
Add semaphore config

### LINKED ISSUE #7: Setup semaphoreci
Ref: https://github.com/bigbinary/neeto-engineering-web/issues/311

### PR DESCRIPTION
**Pull request by datt**
Fixes #7.

### CODE REVIEW

**Comment by datt** [comment]
@sandip-mane Added project in semaphore and semaphore config. Added rubocop auto-correctable changes, still, `495 offenses detected`.

**Comment by sandip-mane** [comment]
@akhil-gautam is it fine to ignore Rubocop for this repo? We are forking honeybadger-ruby gem, in future when we want to rebase, it will cause conflicts.

**Comment by akhil-gautam** [comment]
True, let's ignore this one.

**Comment by sandip-mane** [comment]
@datt _a could you please undo the changes for Rubocop?

**Comment by datt** [comment]
@sandip-mane _a Removed rubocop, there are 7 test failures mostly related to SSL. Can you please check?

**Pull request merged**
